// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFXJRgmK89dbTcldzGXb6BffKXcLyRV1I',
    appId: '1:895171542232:web:ffae2c0bbe5a225dc32bad',
    messagingSenderId: '895171542232',
    projectId: 'appdevs-822b5',
    authDomain: 'appdevs-822b5.firebaseapp.com',
    storageBucket: 'appdevs-822b5.appspot.com',
    measurementId: 'G-4KMTQ78LC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDezpATHvz73TC1iCMELtNI2iBFzdyklZI',
    appId: '1:895171542232:android:8b7200c5a92b9735c32bad',
    messagingSenderId: '895171542232',
    projectId: 'appdevs-822b5',
    storageBucket: 'appdevs-822b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1AdGLHVpavwTi-iDH-WICmJDK0OIRQZk',
    appId: '1:895171542232:ios:cca09051411f6f17c32bad',
    messagingSenderId: '895171542232',
    projectId: 'appdevs-822b5',
    storageBucket: 'appdevs-822b5.appspot.com',
    iosBundleId: 'com.example.medicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1AdGLHVpavwTi-iDH-WICmJDK0OIRQZk',
    appId: '1:895171542232:ios:cca09051411f6f17c32bad',
    messagingSenderId: '895171542232',
    projectId: 'appdevs-822b5',
    storageBucket: 'appdevs-822b5.appspot.com',
    iosBundleId: 'com.example.medicine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFXJRgmK89dbTcldzGXb6BffKXcLyRV1I',
    appId: '1:895171542232:web:8dff5a5ce8966dd8c32bad',
    messagingSenderId: '895171542232',
    projectId: 'appdevs-822b5',
    authDomain: 'appdevs-822b5.firebaseapp.com',
    storageBucket: 'appdevs-822b5.appspot.com',
    measurementId: 'G-125NJGCXE7',
  );
}
